### PR TITLE
[wip] feat: added label and assignee to the create issue

### PR DESCRIPTION
**Pull request by sahil9001**
Because

- (write the reason why we need to consider this PR in a list)

This commit

- (write the summary of all commits in this PR in a list)
Relates to https://github.com/instill-ai/instill-core/issues/1094

### CODE REVIEW

**Comment by sahil9001** [comment]
@jvallesm Can you help me here? I wanted to test the create issue component in pipeline, but I am unable to do so, here is my script:

```
version: v1beta
variable:
  PROJECT_KEY:
    title: "Jira Project Key"
    description: "Jira project key"
    instill-format: string

  JIRA_TOKEN:
    title: "Jira Token"
    description: "Jira API token"
    instill-format: string

  JIRA_EMAIL:
    title: "Jira Email"
    description: "Email associated with Jira account"
    instill-format: string

  JIRA_BASE_URL:
    title: "Jira Base URL"
    description: "Base URL for your Jira instance"
    instill-format: string
  
component:
  jira-0:
    type: jira
    input:
      project-key: ${variable.PROJECT_KEY}
      issue-type:
        issue-type: Epic
      summary: "Sample Epic Summary"
      description: "This is a sample description for the Epic."
    setup:
      token: ${variable.JIRA_TOKEN}
      email: ${variable.JIRA_EMAIL}
      base-url: ${variable.JIRA_BASE_URL}
    task: TASK_CREATE_ISSUE

output:
  output:
    value: ${jira-0.description}
```

When running the pipeline I am getting 204, but the response is empty. Also I can't see the epic in JIRA.

This is the console log,
`{"L":"ERROR","T":"2024-10-03T08:11:03.697Z","M":"Failed to extract ServerMetadata from context"}`

**Comment by chuang8511** [comment]
Hi @sahil9001 ,
Thanks for taking time to take this task.

You have to add the input in the tasks.json for Jira.
[Ref](https://github.com/instill-ai/pipeline-backend/blob/main/pkg/component/CONTRIBUTING.md#tasksjson).

Please feel free to ask any question if you meet the further questions.

**Comment by sahil9001** [comment]
Thanks @chuang8511 , can you help me further, for some reason when I am putting the value in `tasks.json` it doesn't show up on the UI. Do you have a video or something, if you can please share?

**Comment by chuang8511** [comment]
> Do you have a video or something

No, we do not have video.

> it doesn't show up on the UI.

If you make sure the json is right, the reason why it doesn't show up in UI could be
- The component spec is not updated. So, you need to re-run go ./cmd/main again to update it.
- There could be unknown bug in UI, so you could still edit the ymal_recipe and try to push the run button to check if the params are really sending to the working.


> can you help me further

How about you push your modification on json?
So, I can take a look what problem could be.

And, another quick way is to check other json as reference.

**Comment by sahil9001** [comment]
> How about you push your modification on json?
So, I can take a look what problem could be.

Actually I am unclear about what to update in that JSON (as I can't see a field to add there), I am asking for a working example if you have.

What is the problem with my variable input which I was doing earlier?

**Comment by chuang8511** [comment]
Hi @sahil9001 
Could you take a look on this [PR](https://github.com/instill-ai/pipeline-backend/pull/686/files) as reference?
I think it is similar with what you will do.

**Comment by sahil9001** [comment]
> Hi @sahil9001 Could you take a look on this [PR](https://github.com/instill-ai/pipeline-backend/pull/686/files) as reference? I think it is similar with what you will do.

I think this part will come when I need to check my assignee or label changes, currently I am just checking what the base component is by running it, and I am unable to provide an input from the UI.

**Comment by sahil9001** [comment]
https://github.com/instill-ai/pipeline-backend/pull/692#issuecomment-2390795111

See the yaml which I shared above, that is what I am using, when I click on "Run" here, nothing happens. Which means, no information on the frontend regarding the failure and also no issue gets created on the JIRA.

Screenshot 2024-10-04 at 3 04 30 PM

**Comment by kuroxx** [comment]
Hello @sahil9001, have you joined our Discord group yet? May I suggest you attend any of our office hours sessions (every Tuesday at 3 pm BST or Thursday at 6 pm BST) so we can walk-through and troubleshoot your issue together? 

You can join our discord here: https://discord.gg/sevxWsqpGh

**Comment by sahil9001** [comment]
Sure, thanks for this.

**Pull request closed without merging**
