### PR TITLE
feat: make `fetchEmails` async

### PR DESCRIPTION
**Pull request by donno2048**
solves instill-ai/instill-core#1111

### CODE REVIEW

**Comment by donno2048** [comment]
WIP, hence PR title isn't linted please approve for testing workflow to run

**Comment by chuang8511** [comment]
Hi @donno2048 ,
Thanks for your time. Could you help me do a few things?
1. Change the title when the PR is ready to be reviewed. We will start to confirm it when all CI passed.
2. Provide the sample recipe for us that we can easily QA in our sides.

Please feel free to ask us any question! 
Thank you again! 🙇

**Comment by donno2048** [comment]
Sure, I'll change the title when the PR is ready, as for QA, isn't the workflow already doing it?

**Comment by chuang8511** [comment]
Hi @donno2048 , 
Thanks for your question!
The current workflow only QA high level API. It does not test the implementation you do.
In the future, we will have the recipe automation function to make this part efficient.

Before that, we need to ensure the functionality by end to end test through the developers.

**Comment by donno2048** [comment]
My change doesn't affect the function as a whole, only changes the way it is evaluated, so I won't make any new tests as there's nothing new to test...

**Comment by chuang8511** [comment]
I don't mean you have to add a new test case in the codebase.
I mean when we modify the code, we have to do end-to-end test by developers.

For example, in this PR, I will do manual test by this recipe to ensure it works as expected.

```
version: v1beta
component:
    email-0:
        type: email
        task: TASK_READ_EMAILS
        input:
            search:
                limit: 5
                mailbox: Inbox
        setup:
            email-address: ${variable.your_gmail_address}
            password: ${secret.instill-email-component}
            server-address: imap.gmail.com
            server-port: 993
variable:
    your_gmail_address:
        title: your-gmail-address
        instill-format: string
output:
    result:
        title: result
        value: ${email-0.output.emails}
```

Because we already have had this recipe, please help us modify the title.
We will do QA by this recipe when we review it.

Thanks for your contribution! 🙇

**Comment by donno2048** [comment]
Are you just asking me to change the title?  If you already have a recipe to test this with I don't understand what you want..?

**Comment by chuang8511** [comment]
Please just update the title. We will QA on our own.

**Comment by donno2048** [comment]
Done

**Comment by chuang8511** [comment]
@donno2048 
Please make sure your code pass the test locally first.
For component, you could run `go test ./pkg/component/...`

image

**Comment by donno2048** [comment]
Fixed, sorry, I'm on mobile so it's a little complicated to run tests....

**Comment by chuang8511** [comment]
@donno2048 
Thanks for your contribution.
Could you take a look about the rule of [sending PR](https://github.com/instill-ai/pipeline-backend/blob/main/.github/CONTRIBUTING.md#sending-prs)?

Let's follow it to make the commit history clean.

> Make and Commit Changes: Implement your changes and commit them. We encourage you to follow these best practices for commits to ensure an efficient review process:
Adhere to the [conventional commits guidelines](https://www.conventionalcommits.org/) for meaningful commit messages.
Follow the [7 rules of commit messages](https://chris.beams.io/posts/git-commit/) for well-structured and informative commits.
Rearrange commits to squash trivial changes together, if possible. Utilize [git rebase](http://gitready.com/advanced/2009/03/20/reorder-commits-with-rebase.html) for this purpose.

**Comment by donno2048** [comment]
I'll make a new PR with a clean history...

Lots of force pushes here and stuff

**Pull request closed without merging**
