### PR TITLE
feat(json): Support Rename Fields for JSON operator

### PR DESCRIPTION
**Pull request by AkashJana18**
Because
- we want to manipulate JSON data

This commit
- provide the function to rename the json key with different strategies.

### CODE REVIEW

**Comment by chuang8511** [comment]
Hi @AkashJana18 
Is it ready to review?
If it is, could you update your commit message? Then, I will start to review this PR.

And, I noticed that you haven't added the test code. Could you also add the test code?

**Comment by AkashJana18** [comment]
Hey @chuang8511, could you review the PR? I’ve added unit tests and completed the tasks as per my understanding of the requirements. Any additional feedback or guidance on improving the implementation would be really helpful!

**Comment by chuang8511** [comment]
Hi @AkashJana18 , it seems lint not passed.
Could you install the pre-commit and check if all passes?

or, you can install golangci-lint to confirm directly.

Thanks for your contribution!

**Comment by AkashJana18** [comment]
Hey @chuang8511 solved the lint issue

**Comment by kuroxx** [comment]
Hey @AkashJana18 Could you check your test cases since our CI check shows it has not passed [here](https://github.com/instill-ai/pipeline-backend/actions/runs/11730979320/job/32703152137?pr=813)

CleanShot 2024-11-08 at 10 56 27

Whenever you push your commit to this PR it will auto-trigger code checks here so you can check if any test fails first before our engineers review your code 🙏

**Comment by chuang8511** [comment]
please do run and pass it before you request the review.
`$ go test ./pkg/component/operator/json/v0/...`

Thank you!

**Comment by AkashJana18** [comment]
I am a beginner 😅. Sorry for the inconvenience if caused any @kuroxx @chuang8511 

image

**Comment by kuroxx** [comment]
@AkashJana18 Not at all! We can all learn together, especially if it's your first time. We are here to help & learn from each other 💪  I hope the experience thus far has been good and we welcome any feedback if you have! 

So far your PR looks good to me after we re-ran the automated tests. I will pass it to @chuang8511 for further review 🙇

**Comment by chuang8511** [comment]
✅ QAed 
Test Recipe
image

```
# VDP Version
version: v1beta

variable:
  data:
    title: Data
    instill-format: json
  strategy:
    title: Strategy
    instill-format: string
  from:
    title: From
    instill-format: string
  to:
    title: To
    instill-format: string

component:
  json-0:
    type: json
    input:
      json: ${variable.data}
      fields: 
        - from: ${variable.from}
          to: ${variable.to}
      conflict-resolution: ${variable.strategy}
    condition:
    task: TASK_RENAME_FIELDS  


output:
  result:
    title: Result
    value: ${json-0.output}
```

**Comment by chuang8511** [comment]
Hi @AkashJana18 cc @kuroxx 
Thanks for your contribution, I modified and reverted the code a bit. I will merge the code when CI passes.

**Comment by chuang8511** [comment]
@AkashJana18 
Thanks for your contribution! I have merged the code. cc @kuroxx

**Comment by AkashJana18** [comment]
🎉 Huge thanks to @chuang8511 and @kuroxx for your guidance and support throughout this project! From navigating Instill's codebase to implementing the JSON field renaming component, I learned so much in just a few days.
 _I've documented the journey and the solution in this blog post:_
 [From Zero to Merge: Building a JSON Renaming Field Component in Go](https://dev.to/akashjana/from-zero-to-merge-building-a-json-renaming-field-component-in-go-17nh) 🚀. 
Hope you enjoy the read as much as I enjoyed building it!

**Pull request merged**
