### PR TITLE
feat(collection): add task split

### PR DESCRIPTION
**Pull request by chuang8511**
Because

- it make pipeline easier to manipulate array

This commit

- add task split

### CODE REVIEW

**Review by GeorgeWilliamStrong — COMMENTED** [review]
From document perspective, LGTM

**Comment by pinglin** [comment]
@chuang8511 Can we separate all tasks into `task_*` like what the Image operator has done? I found it's getting harder and harder to trace code in a single file across so many components and tasks. cc'd @donch1989 @jvallesm

**Comment by jvallesm** [comment]
> @chuang8511 Can we separate all tasks into `task_*` like what the Image operator has done? I found it's getting harder and harder to trace code in a single file across so many components and tasks. cc'd @donch1989 @jvallesm

@pinglin do you mean in this case or as a convention?

To me it depends on the size of the `main.go` file. When we start a component and we have 1-2 (simple) tasks, I find it beneficial to have everything in a single file vs having several small files. As the component code grows, it makes sense to me to start dividing the logic into files. 

But it isn't a strongly-held opinion, I could do with a convention, too.

**Comment by chuang8511** [comment]
Updated.

**Pull request merged**
